name: 'Docker Test'
description: 'Simulate call to SchemaChange'
inputs:
  schemachange_path:
    description: path where schemachange code is found in the GHA VM
    required: true
    default: /home/runner/work/docker_test_code/docker_test_code
    
  command-line: #input ID
    decription: 'Command line to container'
    required: true
    default: 'Default Input'
outputs:
  time: #output ID
    description: 'The output time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -v ${{ inputs.schemachange_path }}:/schemachange ${{ inputs.command-line }}
    